EXTERNAL_LIBS_PATH = ./external_libs
EXTERNAL_C_SOURCES = $(EXTERNAL_LIBS_PATH)/RTT/RTT/SEGGER_RTT.c\
		$(EXTERNAL_LIBS_PATH)/RTT/Syscalls/SEGGER_RTT_Syscalls_GCC.c

EXTERNAL_ASMM_SOURCES = $(EXTERNAL_LIBS_PATH)/RTT/RTT/SEGGER_RTT_ASM_ARMv7M.S


EXTERNAL_INCLUDES = -I$(EXTERNAL_LIBS_PATH)/RTT/RTT/\
		-I$(EXTERNAL_LIBS_PATH)/RTT/Config/
#EXTERNAL_C_SOURCES = RTT/SEGGER_RTT.c