version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current

    steps:
      - checkout

      - run:
          name: update apt
          command: apt-get update

      - run: 
          name: install tools
          command: apt-get -y install make gcc-arm-none-eabi wget unzip curl

      - run:
          name: build all
          command: chmod +x ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 && ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir sonar_info make all -j 2

      - sonarcloud/scan



orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.0

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: SonarCloud
